// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjwoetsvoggwcygvulkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqd29ldHN2b2dnd2N5Z3Z1bGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTkxNjIsImV4cCI6MjA3MDY3NTE2Mn0.V1xbpzdDdfB8sq5FhwGLQ6uuZw3LfVqvJeNbQ5T5x8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});